# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: foryforx notes
email: NA
author: foryforx
description: >- # this means to ignore newlines until "baseurl:"
  Notes for foryforx.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://foryforx.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
rss:              RSS
twitter_username:
github_username:

# Build settings
markdown: kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true
theme: minima
plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
remote_theme: sighingnow/jekyll-gitbook


toc:
  enabled: true
  h_min: 1
  h_max: 3

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
